// Generated from autoPage/site.config.json. Do not edit this file.
window.SITE_CONFIG = Object.freeze({"siteUrl":"https://mylittlepony2025.github.io","apiBaseUrl":"https://www.api.kuake98.com","name":"夸克98"});
